package com.common.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.core.common.model.Clazz;
import com.core.common.model.Course;
import com.core.common.model.Teacher;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeachercourseclazz<M extends BaseTeachercourseclazz<M>> extends Model<M> implements IBean {

	private Teacher teacher;
	private Course course;
	private Clazz clazz;
	
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTeacherid(java.lang.Long teacherid) {
		set("teacherid", teacherid);
	}

	public java.lang.Long getTeacherid() {
		return getLong("teacherid");
	}

	public void setTeachernumber(java.lang.String teachernumber) {
		set("teachernumber", teachernumber);
	}

	public java.lang.String getTeachernumber() {
		return getStr("teachernumber");
	}

	public void setCourseid(java.lang.Long courseid) {
		set("courseid", courseid);
	}

	public java.lang.Long getCourseid() {
		return getLong("courseid");
	}

	public void setCoursenumber(java.lang.String coursenumber) {
		set("coursenumber", coursenumber);
	}

	public java.lang.String getCoursenumber() {
		return getStr("coursenumber");
	}
	
	public void setClazzid(java.lang.Long clazzid) {
		set("clazzid", clazzid);
	}

	public java.lang.Long getClazzid() {
		return getLong("clazzid");
	}
	
	public void setClazznumber(java.lang.String clazznumber) {
		set("clazznumber", clazznumber);
	}

	public java.lang.String getClazznumber() {
		return getStr("clazznumber");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return getInt("flag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setCreateby(java.lang.String createby) {
		set("createby", createby);
	}

	public java.lang.String getCreateby() {
		return getStr("createby");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

	public void setModifyby(java.lang.String modifyby) {
		set("modifyby", modifyby);
	}

	public java.lang.String getModifyby() {
		return getStr("modifyby");
	}
	
	

	public Clazz getClazz() {
		String sql = Db.getSql("teacher.findClazzByNumber");
		clazz = Clazz.dao.findFirst(sql, getClazznumber());
		return clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public Teacher getTeacher() {
		
		String sql = Db.getSql("teacher.findTeacherByNumber");
		teacher = Teacher.dao.findFirst(sql, getTeachernumber());
		
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Course getCourse() {
		
		String sql = Db.getSql("teacher.findCourseByNumber");
		course = Course.dao.findFirst(sql, getCoursenumber());
		
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

}