package com.common.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.core.common.model.Chapter;
import com.core.common.model.Course;
import com.core.common.model.Part;
import com.core.common.model.Question;
import com.core.common.model.Section;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExperiment<M extends BaseExperiment<M>> extends Model<M> implements IBean {

	private Course course;
	private Chapter chapter;
	private Section section;
	private Part part;
	private Question question;
	
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCourseid(java.lang.Long courseid) {
		set("courseid", courseid);
	}

	public java.lang.Long getCourseid() {
		return getLong("courseid");
	}

	public void setChapterid(java.lang.Long chapterid) {
		set("chapterid", chapterid);
	}

	public java.lang.Long getChapterid() {
		return getLong("chapterid");
	}

	public void setSectionid(java.lang.Long sectionid) {
		set("sectionid", sectionid);
	}

	public java.lang.Long getSectionid() {
		return getLong("sectionid");
	}

	public void setPartid(java.lang.Long partid) {
		set("partid", partid);
	}

	public java.lang.Long getPartid() {
		return getLong("partid");
	}
	
	public void setQuestionid(java.lang.Long questionid) {
		set("questionid", questionid);
	}

	public java.lang.Long getQuestionid() {
		return getLong("questionid");
	}
	
	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return getInt("flag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setCreateby(java.lang.String createby) {
		set("createby", createby);
	}

	public java.lang.String getCreateby() {
		return getStr("createby");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

	public void setModifyby(java.lang.String modifyby) {
		set("modifyby", modifyby);
	}

	public java.lang.String getModifyby() {
		return getStr("modifyby");
	}
	
	
	// 课程
	public Course getCourse() {
		course = Course.dao.findById(getCourseid());
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	// 章
	public Chapter getChapter() {
		chapter = Chapter.dao.findById(getChapterid());
		return chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	// 节
	public Section getSection() {
		section = Section.dao.findById(getSectionid());
		return section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	// 小节
	public Part getPart() {
		part = Part.dao.findById(getPartid());
		return part;
	}

	public void setPart(Part part) {
		this.part = part;
	}

	// 题
	public Question getQuestion() {
		question = Question.dao.findById(getQuestionid());
		return question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}
	

}
