package com.common.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.core.common.model.Chapter;
import com.core.common.model.Course;
import com.core.common.model.Section;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePart<M extends BasePart<M>> extends Model<M> implements IBean {

	private Course course;
	private Chapter chapter;
	private Section section;
	
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return getStr("number");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCourseid(java.lang.Long courseid) {
		set("courseid", courseid);
	}

	public java.lang.Long getCourseid() {
		return getLong("courseid");
	}

	public void setChapterid(java.lang.Long chapterid) {
		set("chapterid", chapterid);
	}

	public java.lang.Long getChapterid() {
		return getLong("chapterid");
	}

	public void setSectionid(java.lang.Long sectionid) {
		set("sectionid", sectionid);
	}

	public java.lang.Long getSectionid() {
		return getLong("sectionid");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return getInt("flag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setCreateby(java.lang.String createby) {
		set("createby", createby);
	}

	public java.lang.String getCreateby() {
		return getStr("createby");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

	public void setModifyby(java.lang.String modifyby) {
		set("modifyby", modifyby);
	}

	public java.lang.String getModifyby() {
		return getStr("modifyby");
	}
	
	

	public Course getCourse() {
		course = Course.dao.findById(getCourseid());
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Chapter getChapter() {
		chapter = Chapter.dao.findById(getChapterid());
		return chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public Section getSection() {
		section = Section.dao.findById(getSectionid());
		return section;
	}

	public void setSection(Section section) {
		this.section = section;
	}
	

}
