package com.common.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.core.common.model.Chapter;
import com.core.common.model.Course;
import com.core.common.model.Experiment;
import com.core.common.model.Part;
import com.core.common.model.Section;
import com.core.common.model.Student;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudentexpertiment<M extends BaseStudentexpertiment<M>> extends Model<M> implements IBean {

	private Course course;
	private Chapter chapter;
	private Section section;
	private Part part;
	private Student student;
	private Experiment experiment;
	
	public Experiment getExperiment() {
		experiment = Experiment.dao.findById(getExperimentid());
		return experiment;
	}

	public void setExperiment(Experiment experiment) {
		this.experiment = experiment;
	}

	public Course getCourse() {
		course = Course.dao.findById(getCourseid());
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Chapter getChapter() {
		chapter = Chapter.dao.findById(getChapterid());
		return chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public Section getSection() {
		section = Section.dao.findById(getSectionid());
		return section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	public Part getPart() {
		part = Part.dao.findById(getPartid());
		return part;
	}

	public void setPart(Part part) {
		this.part = part;
	}

	public Student getStudent() {
		student = Student.dao.findById(getStudentid());
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	
	
	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setStudentid(java.lang.Long studentid) {
		set("studentid", studentid);
	}

	public java.lang.Long getStudentid() {
		return getLong("studentid");
	}

	public void setCourseid(java.lang.Long courseid) {
		set("courseid", courseid);
	}

	public java.lang.Long getCourseid() {
		return getLong("courseid");
	}

	public void setChapterid(java.lang.Long chapterid) {
		set("chapterid", chapterid);
	}

	public java.lang.Long getChapterid() {
		return getLong("chapterid");
	}

	public void setSectionid(java.lang.Long sectionid) {
		set("sectionid", sectionid);
	}

	public java.lang.Long getSectionid() {
		return getLong("sectionid");
	}

	public void setPartid(java.lang.Long partid) {
		set("partid", partid);
	}

	public java.lang.Long getPartid() {
		return getLong("partid");
	}

	public void setExperimentid(java.lang.Long experimentid) {
		set("experimentid", experimentid);
	}

	public java.lang.Long getExperimentid() {
		return getLong("experimentid");
	}

	public void setHfname(java.lang.String hfname) {
		set("hfname", hfname);
	}

	public java.lang.String getHfname() {
		return getStr("hfname");
	}

	public void setHfcontent(java.lang.String hfcontent) {
		set("hfcontent", hfcontent);
	}

	public java.lang.String getHfcontent() {
		return getStr("hfcontent");
	}

	public void setSfname(java.lang.String sfname) {
		set("sfname", sfname);
	}

	public java.lang.String getSfname() {
		return getStr("sfname");
	}

	public void setSfcontent(java.lang.String sfcontent) {
		set("sfcontent", sfcontent);
	}

	public java.lang.String getSfcontent() {
		return getStr("sfcontent");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return getInt("flag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setCreateby(java.lang.String createby) {
		set("createby", createby);
	}

	public java.lang.String getCreateby() {
		return getStr("createby");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

	public void setModifyby(java.lang.String modifyby) {
		set("modifyby", modifyby);
	}

	public java.lang.String getModifyby() {
		return getStr("modifyby");
	}

}
