package com.common.basemodel;

import com.jfinal.plugin.activerecord.Model;

import java.util.List;

import com.core.common.model.Chapter;
import com.core.common.model.Course;
import com.core.common.model.Part;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSection<M extends BaseSection<M>> extends Model<M> implements IBean {

	private Course course;
	private Chapter chapter;
	private List<Part> parts;
	
	
	public List<Part> getParts() {
		parts = Part.dao.find("select * from part where sectionid = ? and flag = 1", getId());
		return parts;
	}

	public void setParts(List<Part> parts) {
		this.parts = parts;
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return getStr("number");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setCourseid(java.lang.Long courseid) {
		set("courseid", courseid);
	}

	public java.lang.Long getCourseid() {
		return getLong("courseid");
	}

	public void setCoursenumber(java.lang.String coursenumber) {
		set("coursenumber", coursenumber);
	}

	public java.lang.String getCoursenumber() {
		return getStr("coursenumber");
	}

	public void setCoursename(java.lang.String coursename) {
		set("coursename", coursename);
	}

	public java.lang.String getCoursename() {
		return getStr("coursename");
	}

	public void setChapterid(java.lang.Long chapterid) {
		set("chapterid", chapterid);
	}

	public java.lang.Long getChapterid() {
		return getLong("chapterid");
	}

	public void setChapternumber(java.lang.String chapternumber) {
		set("chapternumber", chapternumber);
	}

	public java.lang.String getChapternumber() {
		return getStr("chapternumber");
	}

	public void setChaptername(java.lang.String chaptername) {
		set("chaptername", chaptername);
	}

	public java.lang.String getChaptername() {
		return getStr("chaptername");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return getInt("flag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setCreateby(java.lang.String createby) {
		set("createby", createby);
	}

	public java.lang.String getCreateby() {
		return getStr("createby");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

	public void setModifyby(java.lang.String modifyby) {
		set("modifyby", modifyby);
	}

	public java.lang.String getModifyby() {
		return getStr("modifyby");
	}

	public Course getCourse() {
		course = Course.dao.findById(getCourseid());
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Chapter getChapter() {
		chapter = Chapter.dao.findById(getChapterid());
		return chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

}
