package com.core.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("chapter", "id", Chapter.class);
		arp.addMapping("clazz", "id", Clazz.class);
		arp.addMapping("course", "id", Course.class);
		arp.addMapping("experiment", "id", Experiment.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("part", "id", Part.class);
		arp.addMapping("question", "id", Question.class);
		arp.addMapping("section", "id", Section.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("studentexperimentrecord", "id", Studentexperimentrecord.class);
		arp.addMapping("studentexpertiment", "id", Studentexpertiment.class);
		arp.addMapping("teacher", "id", Teacher.class);
		arp.addMapping("teachercourseclazz", "id", Teachercourseclazz.class);
	}
}

