package com.core.common.model;

import com.common.basemodel.BaseChapter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chapter extends BaseChapter<Chapter> {
	public static final Chapter dao = new Chapter().dao();
}
