package com.core.common.model;

import com.common.basemodel.BaseClazz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Clazz extends BaseClazz<Clazz> {
	public static final Clazz dao = new Clazz().dao();
}
