package com.core.common.model;

import com.common.basemodel.BasePart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Part extends BasePart<Part> {
	public static final Part dao = new Part().dao();
}
