package com.core.common.model;

import com.common.basemodel.BaseSection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Section extends BaseSection<Section> {
	public static final Section dao = new Section().dao();
}
