package com.core.common.model;

import com.common.basemodel.BaseStudentexperimentrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studentexperimentrecord extends BaseStudentexperimentrecord<Studentexperimentrecord> {
	public static final Studentexperimentrecord dao = new Studentexperimentrecord().dao();
}
