package com.core.common.model;

import com.common.basemodel.BaseStudentexpertiment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studentexpertiment extends BaseStudentexpertiment<Studentexpertiment> {
	public static final Studentexpertiment dao = new Studentexpertiment().dao();
}
