package com.core.common.model;

import com.common.basemodel.BaseTeachercourseclazz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teachercourseclazz extends BaseTeachercourseclazz<Teachercourseclazz> {
	public static final Teachercourseclazz dao = new Teachercourseclazz().dao();
}
