package com.core.common.model;

import com.common.basemodel.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher().dao();
}
